title: Yoann Saunier - Musicien Ingénieur du Son
email: yoann.saunier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TODO
url: "http://yoann.saunier.me" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
