- name: |
    _O que importa é o caminho_ de Joana Schweizer
  role: "Création sonore et sonorisation"
  medium: danse
  year: 2017
  description: |
    Création sonore en collaboration avec Joana Schweizer (https://anikivovo.wixsite.com/joschweizeranikivovo) pour
	le spectacle de danse et musique "O que importa é o caminho" par la compagnie Aniki Vóvó
  picture:
	https://static.wixstatic.com/media/94593c_f192514622714f0dbf81a0b4bb582cfc~mv2.png/v1/fill/w_834,h_436,al_c,usm_0.66_1.00_0.01/94593c_f192514622714f0dbf81a0b4bb582cfc~mv2.png

- name: |
    _Le Wagon_
  role: "Création de jingle"
  medium: jingle
  year: 2016
  description: |
    Création d'un jingle musical introduisant les captations de cours et autres événements de l'école de code "Le Wagon"
  picture: https://secure.meetupstatic.com/photos/event/7/4/7/2/highres_459869810.jpeg

- name: |
    _Les Témoins - Saison 2_ de Hervé Hadmar
  role: "Arrangements et programmations musicales"
  medium: francetv
  year: 2016
  description: |
	Arrangements et programmations de la musique pour "Les Témoins, saison 2", série policière française en 8 épisodes créée par
	Marc Herpoux et Hervé Hadmar
  picture: http://fr.web.img3.acsta.net/pictures/17/02/15/17/22/040429.jpg

- name: |
    _Chère anorexie_ de Judith du Pasquier
  role: "guitare"
  year: 2016
  medium: arte
  description: |
    Interprétation des guitares enregistrées pour le documentaire "Chère anorexie" de Judith du Pasquier et Sylvie Quesemand Zucca
  picture: http://addoc.net/wp-content/uploads/Unknown-1-1-267x400.png

- name: |
    _Au-delà des murs_ de Hervé Hadmar
  role: "Arrangements et programmations musicales"
  year: 2015
  medium: arte
  description: |
    Programmations musicales pour "Au-delà des murs", mini-série franco-belge en 3 épisodes créée par Hervé Hadmar et Marc Herpoux,
	diffusée le 22 septembre 2016 sur Arte
  picture: https://leschroniquesdecliffhanger.files.wordpress.com/2016/04/au-dela-des-murs.jpg
		   ou
		   http://img.over-blog-kiwi.com/0/21/32/49/20150609/ob_95b306_affiche-addm.jpg

- name: |
    _Qui a peur de Virginia Woolf ?_ d'Edward Albee
  role: "guitare"
  medium: théâtre
  year: 2015
  description: |
	Interprétation des guitares enregistrées pour la pièce "Qui a peur de Virginia Woolf" (Molière 2016) d'Edward Albee, mise en scène par
	Alain Françon et jouée au Théâtre de l’Œuvre
  picture: http://france3-regions.francetvinfo.fr/paris-ile-de-france/sites/regions_france3/files/styles/top_big/public/assets/images/2016/01/22/640x360_7.jpg?itok=FZ2DxYGG

- name: |
    _Malca_
  role: "Guitariste / Bassiste"
  medium: musique
  year: 2015
  description: |
    Guitariste et bassiste du groupe Malca (facebook.com/iammalca )
  picture: https://scontent-cdg2-1.xx.fbcdn.net/v/t31.0-8/13305033_1075261462557722_6716375962818179935_o.jpg?oh=7b2a64ef0c1a64b4c77f57baa0d65492&oe=59BEA4C2

- name: |
    _Les Témoins - Saison 1_ de Hervé Hadmar
  role: "Programmations musicales"
  medium: francetv
  year: 2014
  description: |
    Programmations musicales pour "Les Témoins", série policière française en 6 épisodes, créée par Marc Herpoux et Hervé Hadmar
	et diffusée à partir du 18 mars 2015 sur France 2
  picture: http://www.voirfilms.biz/posterserie/2015/09/19/les-temoins-64.jpg

- name: |
    _Guillaume et les garçons, à table_ de Guillaume Gallienne
  role: "Programmations musicales"
  medium: cinema
  year: 2013
  description: |
    Programmations musicales pour "Les Garçons et Guillaume, à table !", comédie franco-belge écrite et réalisée par
	Guillaume Gallienne (César 2013)
  picture: http://fr.web.img2.acsta.net/pictures/205/298/20529833_20131017171932686.jpg

- name: |
    _KAB_ de Guillaume Gallienne
  role: "Co-fondateur"
  medium: musique
  year: 2013
  description: |
    Co-fondateur, compositeur et producteur du groupe KAB (kabaretmusic.fr )
  picture: https://f4.bcbits.com/img/a4165668923_10.jpg

- name: |
    _Strass_
  role: "Co-fondateur"
  medium: musique
  year: 2013
  description: |
    Co-fondateur, compositeur et producteur du duo de musique électronique Strass (soundcloud.com/strassreleases )
  picture: https://i1.sndcdn.com/avatars-000273327051-81jo4x-t500x500.jpg

- name: |
    _Mélie Fraisse_
  role: "Claviériste / bassiste"
  medium: musique
  year: 2012
  description: |
    Claviériste et bassiste du groupe Mélie Fraisse (meliefraisse.com)
  picture: http://img.over-blog-kiwi.com/1/61/04/44/20151217/ob_a6861b_11889615-10154151231637788-36031064576.jpg

Palmarès
Student Competition @ Audio Engineering Society 132nd convention — Silver Award (Catégorie 3 : Modern Studio) 
Vovox Make the score! 10th Anniversary competition (2013) : 1° place 
Tremplin Fallenfest 2014 (Saison 13) : 1° place pour KAB 
Pimps of Joytime's « Booty Text » Remix Contest (2014) : 1° place 
Burning House’s « PPSD » Remix Contest (2013) : 1° place 
Incredible Polo’s « Feel Ma Peine » Remix Contest (2013) : 1° place 

Bio longue :
Musicien, ingénieur du son et compositeur français né le 28 Janvier 1990 à Mont-Saint-Aignan (Normandie), Yoann Saunier entre au
Conservatoire à rayonnement régional de Rouen à l’âge de 7 ans pour y étudier la guitare classique.
Durant l’adolescence il découvre la musique rock, monte un groupe et fait ses premiers pas dans l’enregistrement sonore et la
production musicale. A sa majorité il part étudier le son à l’image en classe préparatoire Ciné-Sup au Lycée Guist’hau de Nantes où
il se tourne vers les musiques électroniques et la composition de musiques de films. En 2010, il entre au Conservatoire National Supérieur
de Musique et de Danse de Paris, se spécialise dans la Musique Assistée par Ordinateur et décroche cinq ans plus tard le diplôme de
Formation Supérieure au Métiers du Son. Aujourd’hui, il collabore avec divers compositeurs de musiques à l’image ou pour le
théâtre (Eric Demarsan, Marie-Jeanne Serero…), se produit régulièrement sur scène au sein de différents groupes de musiques
actuelles (Kabaret, Malca, Mélie Fraisse…) et réalise parallèlement de nombreux remixes avec son duo de DJ, Strass.

Bio courte :
Musicien, ingénieur du son et compositeur normand spécialisé dans les musiques électroniques. Diplômé de la Formation
Supérieure au Métiers du Son au Conservatoire de Paris, il collabore avec divers compositeurs de musiques à l'image (Eric Demarsan,
Marie-Jeanne Serero…) et se produit régulièrement sur scène dans différents groupes (KAB, Malca, Strass, Mélie Fraisse…)